version: "2.3"

services:
  db:
    image: postgres

  backend:
    image: grafitio/grafit-backend
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  frontend:
    image: grafitio/grafit-frontend
    ports:
      - 3000:80
    restart: always
    depends_on:
      - backend

  documentation:
    image: grafitio/grafit-docs
    restart: always
    ports:
      - "8001:8001"
