version: '2.1'

services:
  backend:
    image: grafit
    build: .
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./backend:/code
    
  documentation:
    restart: always
    build: ./mkdocs
    volumes:
      - ./mkdocs:/code
    ports:
      - "8001:8001"