version: "2.3"

services:
  db:
    image: postgres

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "neo4j/test"

  backend:
    image: grafit-backend
    build:
      context: ./backend
      target: base
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - neo4j

  frontend:
    image: grafit-frontend
    build:
      context: ./frontend
      target: base
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./frontend:/usr/src/grafit
      - /usr/src/grafit/node_modules
    depends_on:
      - backend

  documentation:
    restart: always
    build: ./mkdocs
    volumes:
      - ./mkdocs:/code
    ports:
      - "8001:8001"
