version: "2.3"

services:
  db:
    image: postgres

  neo4j:
    image: neo4j
    environment:
      NEO4J_AUTH: "neo4j/test"

  backend:
    image: grafitio/grafit-backend
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
      - neo4j

  frontend:
    image: grafitio/grafit-frontend
    ports:
      - 3000:80
    restart: always
    depends_on:
      - backend

  documentation:
    image: grafitio/grafit-docs
    restart: always
    ports:
      - "8001:8001"
