site_name: grafit.io
site_description: Shared Knowledge
repo_url: https://github.com/grafit-io/grafit
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/grafit-io">grafit</a>.
dev_addr: 0.0.0.0:8001
docs_dir: "mkdocs/docs"

nav:
  - Home: "index.md"
  - Users: "userdoc/index.md"
  - Developers:
      - Quck Start: "developerdoc/quickstart.md"
      - Containers: "developerdoc/containers.md"
      - API-Authentication: "developerdoc/api/authentication.md"
      - API-Users: "developerdoc/api/users.md"

theme:
  name: readthedocs
